export const galleryData = [
  {
    id: 1,
    image: "https://i.imgur.com/5yeBVeM.jpeg",
    shares: 1,
    views: 24,
    comments: 3,
    likes: 3,
  },
  {
    id: 2,
    image: "https://i.imgur.com/fjXFX93.jpeg",
    shares: 2,
    views: 85,
    comments: 7,
    likes: 19,
  },
  {
    id: 3,
    image: "https://i.imgur.com/ISpNf4j.jpeg",
    shares: 5,
    views: 132,
    comments: 11,
    likes: 42,
  },
  {
    id: 4,
    image: "https://i.imgur.com/DBpznrn.jpeg",
    shares: 8,
    views: 204,
    comments: 16,
    likes: 73,
  },
  {
    id: 5,
    image: "https://i.imgur.com/5yeBVeM.jpeg",
    shares: 6,
    views: 310,
    comments: 25,
    likes: 90,
  },
  {
    id: 6,
    image: "https://i.imgur.com/fjXFX93.jpeg",
    shares: 9,
    views: 540,
    comments: 33,
    likes: 152,
  },
];
